#!/usr/bin/perl
#=============================================================================
# json_set_manageip
#=============================================================================

sub usage {
    print "$0: Update the managed IP of an existing host\n";
    print "Usage: $0 hostname new-ip\n";
    exit;
}

use JSON::Parse ':all';
use Data::Dumper;

require 'zapi_toolkit.pl';

$debug=0;
$debugold=0;

my $host=shift;
my $newip=shift;

unless ($host && $newip) {
    &usage;
}

my $hostpath=&zapi_toolkit::gethostuid($host);
if ($hostpath =~ m|/zport/dmd/|) {
    print "Host $host found at $hostpath, proceeding\n\n"  if ($debug);

    my $data=qq({"uids":["$hostpath"],"hashcheck":"","ip":"$newip"});
    my $output = zapi_toolkit::zcurlpost("device_router","DeviceRouter","resetIp",$data);
    my $success=&zapi_toolkit::catchJsonErrors($output);

} else {
    print STDERR "Host $host not found.\n";
}


exit;

