#!/usr/bin/perl

#=============================================================================
# json_del_groupsystem
#=============================================================================

sub usage {
    print "$0: Delete a host from an existing group or system category\n";
    print "Usage: $0 {group|system}=name hostname [hostname....]\n";
    print "If 'name' = 'list' then print out the available groups/systems and exit\n";
    print "It's ok if the host is not actually in the group/system requested.\n\n";
    exit;
}

use JSON::Parse ':all';
use Data::Dumper;
require 'zapi_toolkit.pl';

$debug=0;
$debugold=0;

my $task=shift;
my ($cat,$name) = split ('=',$task);

unless ($cat =~ /(group|system)/) {
    &usage;
}

my $method;
if ($cat eq 'group') {
    $method="getGroups";
} elsif ($cat eq 'system') {
    $method="getSystems";
} else {
    &usage;
}

#first retrieve list of valid names for $cat
my %catarry=&zapi_toolkit::get_valid_values($method);

if ($name eq "list") {
    foreach my $x (sort keys %catarry) {
	print "$x\n";
    }
    exit;
}

if (exists $catarry{$name}) {
    print "Selected $cat name $name exists... proceeding\n\n" if ($debug);
} else {
    print "Selected $cat name $name DOES NOT EXIST\n";
    exit;
}


$method=~s/get//; #getSystems -> Systems etc.
while (my $host=shift) {
    print "Deleting host $host from $cat $name\n"  if ($debug);
    my $hostpath=&zapi_toolkit::gethostuid($host);
    unless ($hostpath =~ m|/zport/dmd/|) {
	print "Host $host not found\n";
	next;
    }

    print "Host $host found at $hostpath, proceeding\n\n"  if ($debug);
    my $data=qq({"uids":["$hostpath"],"hashcheck":"","uid":"/zport/dmd/${method}${name}"});
    my $output = &zapi_toolkit::zcurlpost("device_router","DeviceRouter","removeDevices",$data);
}


exit;





