#!/usr/bin/perl

#=============================================================================
# json_get_info
#
# By David Pirmann. This script is an interface to the JSON API exposed by the
# "Zenoss Core" product from www.zenoss.org. This script requires "zapi_toolkit" 
# from https://github.com/dpirmann/zenosstools
# See README and the project WIKI on above GITHUB site for more details.
#
# This script is hereby released under GNU General Public License version 2
# See http://www.gnu.org/licenses/gpl-2.0.html for details.
#=============================================================================

sub usage {
    print "Usage: $0 hostname-or-ip [whatinfo]\n";
    print "where hostname or ip must match exactly a device in Zenoss.\n";
    print "Whatinfo is some key like snmpSysName you want about that device\n";
    exit;
}

use JSON::Parse ':all';
require 'zapi_toolkit.pl';

my $debug=1;
my $debugold=0;

my $host=shift;
my $whatinfo=shift;

&usage unless ($host);

#find out the /zport/dmd/host/path for the given host argument
my $hostpath=zapi_toolkit::gethostuid($host);
print "$hostpath\n" if ($debug);

unless ($hostpath =~ m|/zport/dmd|) {
    die "Host not found in Zenoss.\n";
}

#look up whatinfo against hostpath
#getinfo checks for errors before processing its json to return us the value
my %aar=&zapi_toolkit::getinfokey($hostpath);

if ($whatinfo) {
    my $myinfo=$aar{$whatinfo};
    if ($myinfo) {
	print "$myinfo\n";
    }
} else {
    foreach (sort keys %aar) {
	print "$_ : $aar{$_}\n";
    }
}

exit;

