#!/usr/bin/perl

#=============================================================================
# json_get_host_osprocess
#=============================================================================

sub usage {
    print "$0 [-c] hostname [hostname...]\n";
    print "Given a list of HOSTNAMES (or IP), list out the os processes modeled on this device";
    print "Option -c for csv output\n";
    exit;
}

use JSON::Parse ':all';
use Getopt::Std;

require 'zapi_toolkit.pl';

my $debug=0;

getopts('ch',\%opts);
if (defined $opts{'h'}) {
    &usage;
}

if (defined $opts{'c'}) {
    print "Host,ProcessClass,Process,Status,Monitored\n";
} else {
    printf "%-15s %-20.20s %-30.30s %-8.8s %-10.10s\n", "Host", "ProcessClass", "Process", "Status", "Monitored";
    printf "=" x 86 . "\n";
}

while (my $host=shift) {

    #find out the /zport/dmd/host/path for the given host argument
    my $hostpath=zapi_toolkit::gethostuid($host);
    next unless ($hostpath =~ m|/zport/dmd|);
    print "$hostpath\n" if ($debug);

    my $host=$hostpath;
    $host=~ s|/zport.*devices/||;

    #look up hostpath's components
    my $data=qq({"uid":"$hostpath","keys":["status","processName","processClassName","monitored"],"meta_type":"OsProcess","limit":3000});
    my $output = zapi_toolkit::zcurlpost("device_router","DeviceRouter","getComponents",$data);
    my $parsed= parse_json($output);
    my $total = %$parsed->{'result'}->{'totalCount'};

    for (my $i=0;$i<$total;$i++) {
	my $pc=%$parsed->{'result'}->{'data'}[$i]->{'processClassName'};
	my $pn=%$parsed->{'result'}->{'data'}[$i]->{'processName'};
	my $ps=%$parsed->{'result'}->{'data'}[$i]->{'status'};
	my $pm=%$parsed->{'result'}->{'data'}[$i]->{'monitored'};
	if($pm) {$pm="Yes"; } else {$pm="No";}
	
	if (defined $opts{'c'}) {
	    print "$host,$pc,$pn,$ps,$pm\n";
	} else {
	    printf "%-15.15s %-20.20s %-30.30s %-8.8s %-10.10s\n", $host, $pc, $pn, $ps, $pm;
	}
    }
}

exit;

