#!/usr/bin/perl

#=============================================================================
# json_manipulate_event
#
# By David Pirmann. This script is an interface to the JSON API exposed by the
# "Zenoss Core" product from www.zenoss.org. This script requires "zapi_toolkit" 
# from https://github.com/dpirmann/zenosstools
# See README and the project WIKI on above GITHUB site for more details.
#
# This script is hereby released under GNU General Public License version 2
# See http://www.gnu.org/licenses/gpl-2.0.html for details.
#=============================================================================

#=============================================================================
sub usage {
    print "$0: Manipulate an existing event in the zenoss event console\n";
    print "Usage: $0 task eventid\n";
    print "where task is 'close', 'reopen', 'acknowledge', 'unacknowledge', 'detail' \n";
    exit;
}

use JSON::Parse ':all';
require 'zapi_toolkit.pl';

$debug=0;
$debugold=0;

my $task=shift;
my $evid=shift;

unless ($task =~ /^(close|reopen|acknowledge|unacknowledge|detail)$/) {
    &usage;
}

unless ($evid) {
    &usage;
}

print "*** $task, $evid\n" if ($debug);

my $output = &zapi_toolkit::manip_event($task, $evid);

exit;
