#!/usr/bin/perl

#=============================================================================
# json_set_manageip
#
# By David Pirmann. This script is an interface to the JSON API exposed by the
# "Zenoss Core" product from www.zenoss.org. This script requires "zapi_toolkit" 
# from https://github.com/dpirmann/zenosstools
# See README and the project WIKI on above GITHUB site for more details.
#
# This script is hereby released under GNU General Public License version 2
# See http://www.gnu.org/licenses/gpl-2.0.html for details.
#=============================================================================

#=============================================================================
sub usage {
    print <<EFO;

$0: Update the managed IP of an existing host.

Usage: $0 hostname new-ip

EFO

exit;
}

use JSON::Parse ':all';
require 'zapi_toolkit.pl';

$debug=0;
$debugold=0;

my $host=shift;
my $newip=shift;

unless ($host && $newip) {
    &usage;
}

my $hostpath=&zapi_toolkit::gethostuid($host);
if ($hostpath =~ m|/zport/dmd/|) {
    print "Host $host found at $hostpath, proceeding\n\n"  if ($debug);

    my $data=qq({"uids":["$hostpath"],"hashcheck":"","ip":"$newip"});
    my $output = zapi_toolkit::zcurlpost("device_router","DeviceRouter","resetIp",$data);
    my $success=&zapi_toolkit::catchJsonErrors($output);

} else {
    print STDERR "Host $host not found.\n";
}


exit;

