#!/usr/bin/perl

#=============================================================================
# pzenoss_api
#
# By David Pirmann. This script is an interface to the JSON API exposed by the
# "Zenoss Core" product from www.zenoss.org. This script requires "zapi_toolkit" 
# from https://github.com/dpirmann/zenosstools
# See README and the project WIKI on above GITHUB site for more details.
#
# This script is hereby released under GNU General Public License version 2
# See http://www.gnu.org/licenses/gpl-2.0.html for details.
#=============================================================================

sub usage {
print <<EOF;

pzenoss_api is a basic interface to the Zenoss JSON API. It is a perl 
reimplemation of an existing bash zenoss_api script.

Syntax: pzenoss_api "endpoint" "action" "method" "data"

Examples:

pzenoss_api "device_router" "DeviceRouter" "getProductionStates" "{}"
pzenoss_api "device_router" "DeviceRouter" "getDeviceUids" "{\"uid\":\"/zport/dmd/Devices/Server/Linux\"}"

See: http://wiki.zenoss.org/Working_with_the_JSON_API for more examples
EOF

exit;
}

use JSON::Parse ':all';
use Data::Dumper;

require "zapi_toolkit.pl";

#parse our arguments
my $ROUTER_ENDPOINT=shift;
my $ROUTER_ACTION=shift;
my $ROUTER_METHOD=shift;
my $DATA=shift;
my $output;

unless ($ROUTER_ENDPOINT && $ROUTER_ACTION && $ROUTER_METHOD && $DATA) {
    &usage;
}


print "Endpoint = $ROUTER_ENDPOINT\n";
print "Action   = $ROUTER_ACTION\n";
print "Method   = $ROUTER_METHOD\n";
print "Data     = $DATA\n";


$output = &zapi_toolkit::zcurlpost($ROUTER_ENDPOINT,$ROUTER_ACTION,$ROUTER_METHOD,$DATA);
die if &zapi_toolkit::catchErrors($output);

my $parsed=parse_json($output);
print Dumper($parsed);
print "\n";	

exit;

