#!/usr/bin/env python

# easy python/dmd script to print out
# all triggers and their rules

import Globals
from Products.ZenUtils.ZenScriptBase import ZenScriptBase

dmd = ZenScriptBase(connect=True).dmd
from Products.Zuul import getFacade, listFacades

tf = getFacade('triggers')
for t in tf.getTriggers():
    print 'X'*80
    print t['name']
    print 'X'*80
    print t['rule']
    print ""
    print ""
    print ""
