#!/usr/bin/env python

import Globals
from Products.ZenUtils.ZenScriptBase import ZenScriptBase

dmd = ZenScriptBase(connect=True).dmd

#import re
#p = re.compile('/Server/Windows', re.IGNORECASE)

for dev in dmd.Devices.getSubDevices():
    dn=dev.getDeviceName()
    cl=dev.getDeviceClassName()
    gn=dev.getDeviceGroupNames()
    ln=dev.getLocationName()
    ip=dev.getManageIp()
    col=dev.getPerformanceServerName()
    sp=dev.zSnmpCommunity
    sv=dev.zSnmpVer
    print str(dn) + "," + str(cl) + "," + str(gn) + "," + str(ln) + "," + str(ip) + "," + str(col) + "," + str(sp) + "," + str(sv)







