#!/usr/bin/env python

# python script to print event transforms
# cribbed from the Zenoss wiki at
# http://wiki.zenoss.org/Event_Transforms_and_Examples

import Globals
from Products.ZenUtils.ZenScriptBase import ZenScriptBase

dmd = ZenScriptBase(connect=True).dmd

print "The following event classes have transforms associated with them:"
print ""

print 'X'*80
print "/Events"
print 'X'*80
print ""
print dmd.Events.transform
print ""
print ""
print ""

for ec in [ ec for ec in dmd.Events.getSubOrganizers() if ec.transform ]:
    print 'X'*80
    print ec.getOrganizerName()
    print 'X'*80
    print ""
    print ec.transform
    print ""
    print ""
    print ""

