#!/usr/bin/env python

import Globals
from Products.ZenUtils.ZenScriptBase import ZenScriptBase

dmd = ZenScriptBase(connect=True).dmd

#import re
#p = re.compile('/Server/Windows', re.IGNORECASE)

for dev in dmd.Devices.getSubDevices():
    for cc in dev.getDeviceComponents():
        if cc.id.find('httpcomp') >= 0:
            print cc.hostname + "," + cc.url + "," + cc.port + "," + cc.eventComponent + "," + cc.eventClass






