#!/usr/bin/env python

import sys
import time
import Globals
from Products.ZenUtils.ZenScriptBase import ZenScriptBase

dmd = ZenScriptBase(connect=True).dmd

zendev = dmd.Devices.findDevice('*')
mwin=zendev.maintenanceWindowSearch()
 
colList=[]
for c in mwin:
    colList.append(c)
colList.sort()
 
tuplist=[]
for c in zendev.maintenanceWindowSearch():
    ob=c.getObject()
    devlist=[]
    for d in ob.fetchDevices():
        devlist.append(d.id)
    devlist.sort()
    if ob.started:
        startedTime=time.strftime("%a, %d %b %Y %H:%M:%S +0000", time.localtime(ob.started))
    else:
        startedTime='None'
    if ob.start:
        startTime=time.strftime("%a, %d %b %Y %H:%M:%S +0000", time.localtime(ob.start))
    else:
        startedTime='None'
    tup=( ob.displayName(), str(ob.target()), ob.enabled, startTime, ob.duration, ob.repeat, startedTime, devlist)
    tuplist.append(tup)
tuplist.sort()
 
for i in tuplist:
    print('Maintenance Window %s Target is %s Enabled is %s Start Time is %s Duration is %s mins Repeat is %s Started Time is %s \n\n' % (i[0], i[1], i[2], i[3], i[4], i[5], i[6] ))
    print(' Devices for this maintenance window are %s \n' % (i[7]))
    print('\n')
 
 

